name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Build and package
        run: make package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/clicky-linux-amd64.tar.gz
            bin/clicky-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
